### ISSUE TITLE
XSS: False positive

### ISSUE THREAD

**Issue by Zaulao** [corazawaf/libinjection-go#14]
Any string that starts with `on` and ends with `==` is matching for XSS.
Examples: `online==` , `onAAAAA==` , `onfoobar==`

These strings can occur in case of receiving legitimate content encoded in base64

**Comment by jcchavezs** [comment]
Related to https://github.com/libinjection/libinjection/issues/30

**Comment by sundarv85** [comment]
This issues seems to be now closed here https://github.com/libinjection/libinjection/pull/7

**Comment by jcchavezs** [comment]
Up to port the change?
